<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPfFxxbx\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPfFxxbx/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPfFxxbx.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPfFxxbx\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerPfFxxbx\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'PfFxxbx',
    'container.build_id' => 'c5d06130',
    'container.build_time' => 1639146217,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPfFxxbx');
