<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerE4VlfOE\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerE4VlfOE/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerE4VlfOE.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerE4VlfOE\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerE4VlfOE\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'E4VlfOE',
    'container.build_id' => 'c3a36666',
    'container.build_time' => 1637441957,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerE4VlfOE');
