<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHNkfyDx\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHNkfyDx/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHNkfyDx.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHNkfyDx\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerHNkfyDx\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'HNkfyDx',
    'container.build_id' => 'e4cd868f',
    'container.build_time' => 1638884709,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHNkfyDx');
